manifest_version = 2
name = "Static content"
description = "Apply performance, security and usability upgrades to static bucket services such as Google Cloud Storage or AWS S3."
authors = ["<oss@fastly.com>"]
language = "rust"
service_id = "7lXJe8YK06iDN01mkYvrhp"

[setup]

  [setup.backends]

    [setup.backends.bucket_origin]
      address = "mock-s3.edgecompute.app"
      port = 443
